apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: job-runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-runner-role
subjects:
- kind: ServiceAccount
  name: job-runner
  namespace: default
