apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-api
  name: my-api-service
spec:
  ports:
  - port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: my-api
status:
  loadBalancer: {}
