apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-api
  name: my-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-api
    spec:
      containers:
      - image: blog-api:0.1
        name: my-blog-api
        resources: {}
status: {}
